opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
grafana:
  enabled: false
prometheus:
  enabled: false
opensearch:
  enabled: false

components:
  accountingService:
    enabled: false
  adService:
    podAnnotations:
      ownedBy: josh
      product: otel-demo-app
      costCentre: dynatrace1
      supportInfo: |+
        ## Ad Service Issue Support Information
        The adService can be debugged within the Live Debugger
        by clicking on this link [Debug Service](https://qcx76851.apps.dynatrace.com/ui/apps/dynatrace.devobs.debugger/redirect/?integration=dashboard&org=qcx76851&labels=[%22k8s.container.name:adservice%22])

default:
  env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.labels['app.kubernetes.io/component']"
    - name: OTEL_COLLECTOR_NAME
      value: 'dynatrace-collector-opentelemetry-collector'
